Feat/handle obj files
Njord201/Raytracer pull request #102
Opened 2024-05-11 18:01 UTC by mathieurobert1

Handle the OBJ file:
file:///home/mrobert/a.OOP/tek2/Raytracer/screenshots/holycow.ppm

2024-05-11 18:08 UTC, theophile-jr approved these changes

2024-05-11 18:32 UTC, Njord201 requested changes

2024-05-11 18:32 UTC, Njord201 commented on include/Parser/Factory.hpp
>  #include "Primitives/Cone.hpp"
```suggestion
#include "Lights/Point.hpp"
#include "Lights/Ambient.hpp"
#include "Primitives/Mesh.hpp"
#include "Primitives/Cone.hpp"
```

2024-05-11 18:32 UTC, Njord201 commented on include/Parser/ParserObj.hpp
Describe all functions with doxygen

2024-05-11 18:32 UTC, Njord201 commented on include/Parser/ParserObj.hpp
> +        std::vector<std::tuple<int, int, int, bool>>   _faces;
Allign the variable with the other

2024-05-11 18:32 UTC, Njord201 commented on include/Parser/ParserObj.hpp
> +        std::vector<std::tuple<int, int, int, bool>>   _faces;
```suggestion
        std::vector<std::tuple<int, int, int, bool>>            _faces;
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief compute the hit point of a Mesh with a ray
```suggestion
         * @brief Compute the hit point of a Mesh with a ray.
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief Construct a new Mesh object.
```suggestion
         * @brief Construct a new mesh object.
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief Destroy the Mesh object.
```suggestion
         * @brief Destroy the mesh object.
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief Get the Normal of the object.
```suggestion
         * @brief Get the normal of the object.
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief Set the Material.
```suggestion
         * @brief Set the material.
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief Get the Material object.
```suggestion
         * @brief Get the material object.
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief Add a Primitive to the Mesh.
```suggestion
         * @brief Add a primitive to the mesh.
```

2024-05-11 18:32 UTC, Njord201 commented on include/Primitives/Triangle.hpp
>               */
```suggestion
            /**
             * @brief Destroy the triangle object.
             *
             */
```

2024-05-12 08:21 UTC, Njord201 requested changes

2024-05-12 08:21 UTC, Njord201 commented on include/Primitives/Mesh.hpp
> +         * @brief Compute the hit point of a Mesh with a ray
```suggestion
         * @brief Compute the hit point of a Mesh with a ray.
```

2024-05-12 08:44 UTC, Njord201 approved these changes
Good job !

2024-05-12 09:19 UTC, AxelF44 approved these changes

2024-05-12 11:58 UTC, theophile-jr approved these changes

2024-05-12 12:07 UTC, merged