feat: --help in core
Njord201/Raytracer pull request #29
Opened 2024-04-30 12:52 UTC by theophile-jr

Just add --help to raytracer

2024-04-30 20:43 UTC, Njord201 approved these changes

2024-05-01 07:11 UTC, mathieurobert1 submitted a review, later dismissed

2024-05-01 13:58 UTC, AxelF44 approved these changes

2024-05-01 14:29 UTC, Njord201 requested changes

2024-05-01 14:29 UTC, Njord201 commented on src/Core/main.cpp
> +    std::cout << "Welcome in the Raytracer!" << std::endl;
Remove this line

2024-05-01 14:35 UTC, mathieurobert1 submitted a review, later dismissed

2024-05-02 21:47 UTC, Njord201 approved these changes
Thank's and good job !

2024-05-03 06:52 UTC, mathieurobert1 approved these changes

2024-05-03 11:31 UTC, merged