Feat/compute hit color
Njord201/Raytracer pull request #40
Opened 2024-05-02 21:21 UTC by mathieurobert1

Compute hit colors based on the primitive's material (flat color currently) and the lights.

I created this three lights computations: Ambient, Punctual and Directional.

More details : #36

2024-05-02 21:22 UTC, theophile-jr submitted a review, later dismissed

2024-05-02 21:46 UTC, Njord201 requested changes

2024-05-02 21:46 UTC, Njord201 commented on include/Lights/Directional.hpp
> +         * @return double
Please fix the return type in documentation

2024-05-02 21:46 UTC, Njord201 commented on include/Lights/Point.hpp
>          Math::Point3D getPosition(void) const;
Please fix the return type in documentation

2024-05-02 21:46 UTC, Njord201 commented on src/Plugins/Primitives/Plane/Plane.cpp
> +Math::Point3D Primitive::Plane::computeColor(const Math::Point3D& hitPoint, const Light::LightsContainer& lights) const
Create an Issue an a commentary for TODO

2024-05-03 08:07 UTC, Njord201 requested changes

2024-05-03 08:07 UTC, Njord201 commented on include/Lights/Directional.hpp
>          Math::Point3D getPosition(void) const;
Same herek, the type of return is not the same in documentation

2024-05-03 08:38 UTC, Njord201 approved these changes

2024-05-03 11:35 UTC, AxelF44 approved these changes

2024-05-03 11:54 UTC, merged