feat/ documentation technical + user
Njord201/Raytracer pull request #85
Opened 2024-05-09 16:08 UTC by theophile-jr

2024-05-09 17:05 UTC, Njord201 requested changes

2024-05-09 17:05 UTC, Njord201 commented on doc/.gitkeep
Remove this file.

2024-05-10 08:16 UTC, AxelF44 requested changes

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Factory.hpp
> +         * @brief Create a type component
```suggestion
         * @brief Create a type component.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Factory.hpp
> +         * @brief Register a type component
```suggestion
         * @brief Register a type component.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Factory.hpp
> +         * @brief Create a type component
```suggestion
         * @brief Create a type component.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Factory.hpp
> +         * @brief Register a type component
```suggestion
         * @brief Register a type component.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +                 * @brief Exception to throw when there is an error in parsing
```suggestion
                 * @brief Exception to throw when there is an error in parsing.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +                /* @brief Return the message of error
```suggestion
                /* @brief Return the message of error.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +             * @brief Parse the Camera settings
```suggestion
             * @brief Parse the Camera settings.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +             * @brief Parse the Primitives settings
```suggestion
             * @brief Parse the Primitives settings.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +             * @brief Parse the Lights settings
```suggestion
             * @brief Parse the Lights settings.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +             * @brief Parse the value of settings
```suggestion
             * @brief Parse the value of settings.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +             * @brief Parse imports of scenes
```suggestion
             * @brief Parse imports of scenes.
```

2024-05-10 08:16 UTC, AxelF44 commented on include/Parser/Scene.hpp
> +             * @brief Parse the imported scene
```suggestion
             * @brief Parse the imported scene.
```

2024-05-10 08:35 UTC, mathieurobert1 reviewed
Nice job ! You just have to finish the user documentation.

2024-05-10 14:27 UTC, Njord201 requested changes
See my update on technique_documentation.pdf and utilisateur_documentation.pdf. Also rename this files in english.

2024-05-10 15:23 UTC, AxelF44 approved these changes, later dismissed

2024-05-10 16:56 UTC, mathieurobert1 submitted a review, later dismissed
Seems good

2024-05-10 17:23 UTC, AxelF44 submitted a review, later dismissed

2024-05-11 09:25 UTC, AxelF44 submitted a review, later dismissed

2024-05-11 13:10 UTC, mathieurobert1 approved these changes, later dismissed
You have two request unresolved

2024-05-11 17:47 UTC, AxelF44 submitted a review, later dismissed

2024-05-11 17:54 UTC, mathieurobert1 approved these changes, later dismissed

2024-05-12 13:23 UTC, AxelF44 approved these changes

2024-05-12 13:26 UTC, Njord201 approved these changes

2024-05-12 13:31 UTC, merged