Add antialiasing by supersampling
Njord201/Raytracer pull request #91
Opened 2024-05-10 19:18 UTC by AxelF44

Hello Team,

I've Implemented the antialiasing throught supersampling!

Here are the result of a sphere after an antialiasing of 2:
![image](https://github.com/Njord201/Raytracer/assets/114805962/d48d3680-2cfe-408a-9368-cb902b96a4f4)

And here the result whitout antialiasing:

2024-05-10 19:33 UTC, theophile-jr requested changes
Looks fine. Just small correction but not code ;)

2024-05-10 19:33 UTC, theophile-jr commented on tests/files_examples/subjects/rotation_test.cfg
>      fieldOfView = 72.0; # In degree
degrees ?

2024-05-10 20:31 UTC, Njord201 requested changes
Some little request and two questions

2024-05-10 20:31 UTC, Njord201 commented on include/Camera/Camera.hpp
> +         *
```suggestion
         * @brief Get the antialiasing object.
         *
```

2024-05-10 20:31 UTC, Njord201 commented on include/Camera/Camera.hpp
> +         * @brief Set the Antialiasing object.
```suggestion
         * @brief Set the antialiasing object.
```

2024-05-10 20:31 UTC, Njord201 commented on include/Camera/CameraBuilder.hpp
> +         * @brief Set the Antialiasing object.
```suggestion
         * @brief Set the antialiasing object.
```

2024-05-10 20:31 UTC, Njord201 commented on include/Camera/CameraBuilder.hpp
> +        Raytracer::CameraBuilder&  setAntialiasing(int antialiasing);
```suggestion
        Raytracer::CameraBuilder& setAntialiasing(int antialiasing);
```

2024-05-10 20:31 UTC, Njord201 commented on include/Camera/CameraBuilder.hpp
>           *
```suggestion
         *
```

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +
```suggestion

```

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +
```suggestion

```

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +
```suggestion

```

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +
```suggestion

```

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +
```suggestion

```

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +
```suggestion

```

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +            for (int sy = 0; sy < supersamplingFactor; sy++) {
What does "sy" means ?

2024-05-10 20:31 UTC, Njord201 commented on src/Core/Renderer.cpp
> +                for (int sx = 0; sx < supersamplingFactor; sx++) {
What does sx means ?

2024-05-11 07:55 UTC, mathieurobert1 reviewed
Just resolves all request of @Njord201

2024-05-11 09:15 UTC, AxelF44 commented on tests/files_examples/subjects/rotation_test.cfg
>      fieldOfView = 72.0; # In degree
Yes in degree

2024-05-11 09:30 UTC, mathieurobert1 requested changes
You inverse the image:
![image](https://github.com/Njord201/Raytracer/assets/114564526/35c69ec2-c85a-4e7b-994a-9f5305e46388)
instead of :
![image](https://github.com/Njord201/Raytracer/assets/114564526/5eb9a83e-29bf-4286-9f4f-22885476466f)

2024-05-11 09:30 UTC, mathieurobert1 commented on src/Core/Renderer.cpp
> +        for (int y = 0; y < imageHeight; y++) {
Be careful, you inverse the image: 
```suggestion
        for (int y = imageHeight; y >= 0; y--) {
```

2024-05-11 09:53 UTC, Njord201 approved these changes
Good job

2024-05-11 09:56 UTC, mathieurobert1 requested changes
It's still inverse, but now in the vertical way:
![image](https://github.com/Njord201/Raytracer/assets/114564526/f90c82a7-e3bc-4862-a00d-ffd68f3aef1d)
Instead of :
![image](https://github.com/Njord201/Raytracer/assets/114564526/53b6ef0c-6908-4bb7-bb8c-7d6ba8ad4d00)

2024-05-11 10:17 UTC, Njord201 requested changes

2024-05-11 10:17 UTC, Njord201 commented on include/Camera/Camera.hpp
> +         * @param antialiasing Value of antialiasing
```suggestion
         * @param antialiasing value of antialiasing
```

2024-05-11 10:20 UTC, mathieurobert1 approved these changes
Perfect this time !

2024-05-11 10:26 UTC, mathieurobert1 approved these changes

2024-05-11 12:30 UTC, Njord201 submitted a review, later dismissed
Good job Mister Fradet

2024-05-11 12:34 UTC, theophile-jr submitted a review, later dismissed

2024-05-11 17:50 UTC, mathieurobert1 approved these changes

2024-05-11 18:52 UTC, Njord201 approved these changes

2024-05-11 18:52 UTC, merged